# Generated by Django 5.0.3 on 2024-03-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=10)),
                ('admission_email', models.EmailField(max_length=254, unique=True)),
                ('admission_state', models.CharField(max_length=50)),
                ('admission_city', models.CharField(max_length=50)),
                ('admission_pincode', models.CharField(max_length=6)),
                ('admission_department', models.CharField(max_length=50)),
            ],
        ),
    ]
